### PR TITLE
Cleaned-up the image

### PR DESCRIPTION
**Pull request by Cybornut**
Why? Because I can, so I did.

### CODE REVIEW

**Comment by rtm516** [comment]
This commit is fine but thinking about it we should probably move all the bots images into a folder on here so they can be used without worry that they get removed from discord.
Maybe something like `GeyserDiscordBot/src/main/resources/assets/tag_images/xxxx.png`?
If you can do that in this PR, great but if not then it can be done in another and ill raise an issue.

**Comment by Chew** [comment]
You'd have to add support for uploading files. There's always something like Imgur for permanence, which would be easier and save bandwidth.

**Comment by lukeeey** [comment]
> You'd have to add support for uploading files. There's always something like Imgur for permanence, which would be easier and save bandwidth.

Shove it in the Geyser website repo under a images folder or something

**Comment by Chew** [comment]
cdn.geysermc.org confirmed 😎

**Comment by Cybornut** [comment]
> GeyserDiscordBot/src/main/resources/assets/tag_images/xxxx.png

**Comment by Cybornut** [comment]
I closed by accident, can I unclose it somehow?
nvm

**Comment by Cybornut** [comment]
> I closed by accident, can I unclose it somehow? nvm

nvm found it

**Comment by Cybornut** [comment]
> This commit is fine but thinking about it we should probably move all the bots images into a folder on here so they can be used without worry that they get removed from discord. Maybe something like `GeyserDiscordBot/src/main/resources/assets/tag_images/xxxx.png`? If you can do that in this PR, great but if not then it can be done in another and ill raise an issue.

Uploaded in PR in GeyserDiscordBot/src/main/resources/assets/new_plshelp.png

But how do I refer it on the tag itself?
what's the syntax, just replace the http link with:`../src/main/resources/assets/new_plshelp.png`  ?

Sorry kinda noob

**Comment by Chew** [comment]
https://raw.githubusercontent.com/GeyserMC/GeyserDiscordBot/master/src/main/resources/assets/new_pleasehelp.png

**Comment by Cybornut** [comment]
> https://raw.githubusercontent.com/GeyserMC/GeyserDiscordBot/master/src/main/resources/assets/new_pleasehelp.png

on it

**Review by rtm516 — APPROVED** [review]

**Pull request merged**
