### PR TITLE
Add a tag for invalid YAML syntax

### PR DESCRIPTION
**Pull request by SocMinarch**
This seems to be an error caused by YAML files containing invalid YAML syntax. Although it isn't necessarily Geyser or Floodgate that causes it, it has occurred when Floodgate's prefix was somehow unquoted and the prefix was a YAML special character.

### CODE REVIEW

**Comment by Camotoy** [comment]
I'm pretty sure we fixed this...?

**Comment by SocMinarch** [comment]
The Floodgate prefix was just an example, the error can be triggered by invalid YAML syntax anywhere in the config files

**Comment by Jens-Co** [comment]
> I'm pretty sure we fixed this...?

This was indeed fixed, but it could be useful to put in ErrorAnalyzer. This way we can let people know what is wrong and how to fix the issue.

**Comment by SocMinarch** [comment]
Also, it's entirely possible that even after the fix, someone could manually break it

**Comment by Camotoy** [comment]
Have we seen this since the prefix was fixed?

**Pull request closed without merging**
