### PR TITLE
adding the windows 10 loopback tag

### PR DESCRIPTION
**Pull request by Jens-Co**
might be useful, Also if someone get a better description feel free to comment.

### CODE REVIEW

**Review by Camotoy — CHANGES_REQUESTED** [review]
It's fine enough but I think this should be addressed in Geyser instead.

**Comment by Chew** [comment]
If that's the case then this should be merged but instead with "Please upgrade your Geyser" or something

**Comment by Jens-Co** [comment]
We could catch the npe in geyser if(ip == null { ip = InetAddress.getLocalHost().getHostAddress(); } and send message on loadup.

**Comment by onebeastchris** [comment]
even though the geyser connectiontest command could check for this, a tag like this one would be insanely helpful

**Comment by Tim203** [comment]
See #261

**Pull request closed without merging**
