### PR TITLE
Create tag for mojang bweaking fingies

### PR DESCRIPTION
**Pull request by YHDiamond**

### CODE REVIEW

**Comment by Konicai** [comment]
That issue string is likely way too general

`Caused by: java.lang.IllegalArgumentException: Name and ID cannot both be blank` would likely be better

Honestly I don't think this is necessary because the vast majority of people using Geyser has already swarmed the discord and figured it out. New users are going to download the latest version of floodgate, and there's only going to be a small amount of people who occasionally boot up an old floodgate. Really all I'm saying is that its not a permanent problem that will stick around

**Comment by YHDiamond** [comment]
Ye I'm aware but just for the next week it'll be helpful

**Comment by Camotoy** [comment]
Change the string like Konica suggested and I will merge.

**Comment by YHDiamond** [comment]
done

**Review by Camotoy — APPROVED** [review]

**Pull request merged**
