### PR TITLE
Rory.tag - New and improved!

### PR DESCRIPTION
**Pull request by 7man7LMYT**
Updated the PR so it would use the new JDA branch.

### CODE REVIEW

**Comment by rtm516** [comment]
Not relevant to the bot

**Comment by Heath123** [comment]
> Not relevant to the bot

I completely disagree:
- We already have !!cat
- We have a `fun` category of tags, so tags definitely aren’t always completely serious 
- Rory is more relevant to Geyser than the vibe cat

**Comment by HelveticaToast** [comment]
Roryphobia

**Comment by Heath123** [comment]
Also:

**Comment by Heath123** [comment]
image

**Comment by humematt190** [comment]
come onnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn why don't you just add it like who even cares if t has nothing to do with geyser

**Comment by HelveticaToast** [comment]
please stop marking the comments as off topic I am Crying

**Pull request closed without merging**
