### PR TITLE
Update and rename java16.tag to java17.tag

### PR DESCRIPTION
**Pull request by YHDiamond**
Hmm im sure you can figure out what this does

### CODE REVIEW

**Review by Camotoy — CHANGES_REQUESTED** [review]
I'd rather set this up as a mirror, as we still require Java 16 as a minimum.

**Comment by Camotoy** [comment]
Geyser does not require Java 17.

**Comment by YHDiamond** [comment]
I am very confused right now. I thought we required java 17?

**Comment by Chew** [comment]
Minecraft 1.18 requires it, but since we still support 1.17, which requires 16, we kept it at 16.

**Comment by Camotoy** [comment]
More specifically, there's no practical reason for the codebase to require Java 17. There's like two new features.

**Review by Camotoy — APPROVED** [review]

**Pull request merged**
