### PR TITLE
Create rory.tag

### PR DESCRIPTION
**Pull request by 7man7LMYT**
redned asked for it

### CODE REVIEW

**Review by Konicai — APPROVED** [review]

**Review by BlAnKcOd3 — CHANGES_REQUESTED** [review]
maybe have randomized rory pics

**Comment by 7man7LMYT** [comment]
> maybe have randomized rory pics

we do but idk how to lol

**Comment by 7man7LMYT** [comment]
no rory!? 😔

**Comment by YHDiamond** [comment]
Rory pls

**Comment by E404NNF** [comment]
no !!rory = bad dsicoirodr server :x:

**Review by Chew — CHANGES_REQUESTED** [review]
Rory...

**Comment by 7man7LMYT** [comment]
got it

**Comment by lukeeey** [comment]
Did he though

**Comment by Chew** [comment]
Did who

**Comment by 7man7LMYT** [comment]
rory

**Comment by Chew** [comment]
Redned I think

**Comment by 7man7LMYT** [comment]
redned did i'll add proof

**Comment by 7man7LMYT** [comment]
> Did he though

image

**Comment by lukeeey** [comment]
oh lord

**Comment by 7man7LMYT** [comment]
welp
this is like invalid now :(

**Pull request closed without merging**
